### ISSUE TITLE
Impossible tu build under RPI 3 and Debian 10 64 

### ISSUE THREAD

**Issue by MichaelBitard** [badaix/snapcast#848]
**Describe the bug**
`make` should work under debian 10 on a raspberry pi 3.

The error seems related to `player/alsa_player.cpp:79:53` where the function has_value does not exist

**Steps to Reproduce**
1. Install debian 10 on a RPI 3
2. Install all prerequisites
3. `make`

**Environment details**
- OS: Linux rpi3-20210209 4.19.0-16-arm64 #1 SMP Debian 4.19.181-1 (2021-03-19) aarch64 GNU/Linux
- Snapcast version [0.24.0 and master]
- self compiled

```log
make client
make -C client
make[1]: Entering directory '/home/pi/snapcast-0.24.0/client'
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_OPUS -DHAS_SOXR -DVERSION=\"0.24.0\" -I. -I.. -I../common -pthread -DHAS_VORBIS -DHAS_ALSA -DHAS_PULSE -DHAS_AVAHI -DHAS_DAEMON -c player/alsa_player.cpp -o player/alsa_player.o
player/alsa_player.cpp: In constructor 'player::AlsaPlayer::AlsaPlayer(boost::asio::io_context&, const ClientSettings::Player&, std::shared_ptr<Stream>)':
player/alsa_player.cpp:79:53: error: 'class boost::optional<std::chrono::duration<long int, std::ratio<1, 1000000> > >' has no member named 'has_value'; did you mean 'value'?
     LOG(INFO, LOG_TAG) << "Using " << (buffer_time_.has_value() ? "configured" : "default")
                                                     ^~~~~~~~~
                                                     value
player/alsa_player.cpp:80:121: error: 'class boost::optional<unsigned int>' has no member named 'has_value'; did you mean 'value'?
                        << " buffer_time: " << buffer_time_.value_or(BUFFER_TIME).count() / 1000 << " ms, " << (periods_.has_value() ? "configured" : "default")
                                                                                                                         ^~~~~~~~~
                                                                                                                         value
make[1]: *** [Makefile:123: player/alsa_player.o] Error 1
make[1]: Leaving directory '/home/pi/snapcast-0.24.0/client'
make: *** [Makefile:14: client] Error 2
```

**Comment by MichaelBitard** [comment]
Update: This works on snapcast 0.23.0, so the problem appeared 0.24.0 and is still on master

**Comment by kingosticks** [comment]
I think the preferred method is now to use cmake. You can follow the recipe at https://github.com/badaix/snapcast/blob/master/.github/workflows/ubuntu.yml

**Comment by MichaelBitard** [comment]
Thanks, I'll look into it, and if that's indeed the preferred method, I'll create a PR to update the documentation: https://github.com/badaix/snapcast/blob/master/doc/build.md
