### ISSUE TITLE
Make error with develop branch

### ISSUE THREAD

**Issue by gerroon** [badaix/snapcast#630]
Trying to build it on Debian Testing. 

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 9.3.0-13' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-F9gimE/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
gcc version 9.3.0 (Debian 9.3.0-13) 


```

```
make
make -C client
make[1]: Entering directory '/tmp/snapcast/client'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/tmp/snapcast/client'
make -C server
make[1]: Entering directory '/tmp/snapcast/server'
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_VORBIS -DHAS_VORBIS_ENC -DHAS_OPUS -DVERSION=\"0.20.0\" -I. -I.. -I../common -DHAS_AVAHI -DHAS_DAEMON -pthread -c snapserver.cpp -o snapserver.o
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_VORBIS -DHAS_VORBIS_ENC -DHAS_OPUS -DVERSION=\"0.20.0\" -I. -I.. -I../common -DHAS_AVAHI -DHAS_DAEMON -pthread -c config.cpp -o config.o
g++ -O2  -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-function -DBOOST_ERROR_CODE_HEADER_ONLY -DHAS_FLAC -DHAS_OGG -DHAS_VORBIS -DHAS_VORBIS_ENC -DHAS_OPUS -DVERSION=\"0.20.0\" -I. -I.. -I../common -DHAS_AVAHI -DHAS_DAEMON -pthread -c control_server.cpp -o control_server.o
In file included from control_server.cpp:24:
control_session_http.hpp:72:46: error: ‘tcp_stream’ is not a member of ‘beast’; did you mean ‘ostream’?
   72 |     std::unique_ptr<websocket::stream<beast::tcp_stream>> ws_;
      |                                              ^~~~~~~~~~
      |                                              ostream
control_session_http.hpp:72:46: error: ‘tcp_stream’ is not a member of ‘beast’; did you mean ‘ostream’?
   72 |     std::unique_ptr<websocket::stream<beast::tcp_stream>> ws_;
      |                                              ^~~~~~~~~~
      |                                              ostream
control_session_http.hpp:72:46: error: template argument 1 is invalid
control_session_http.hpp:72:56: error: template argument 1 is invalid
   72 |     std::unique_ptr<websocket::stream<beast::tcp_stream>> ws_;
      |                                                        ^~
control_session_http.hpp:72:56: error: template argument 2 is invalid
make[1]: *** [Makefile:110: control_server.o] Error 1
make[1]: Leaving directory '/tmp/snapcast/server'
make: *** [Makefile:11: server] Error 2

```

**Comment by badaix** [comment]
Looks like your boost version is too old. Please use cmake and follow the build instructions regarding boost:

 > Snapcast depends on boost 1.70 or higher. Since it depends on header only boost libs, boost does not need to be installed, but the boost include path must be set properly: download and extract the latest boost version and add the include path, e.g. calling make with prepended ADD_CFLAGS: ADD_CFLAGS="-I/path/to/boost_1_7x_0/" make.
For cmake you must add the path to the -DBOOST_ROOT flag: cmake -DBOOST_ROOT=/path/to/boost_1_7x_0

**Comment by gerroon** [comment]
Thanks, thankfully Debian testign had 1.7 It works now.

**Comment by badaix** [comment]
Yes, they are compatible

**Comment by gerroon** [comment]
@badaix 

Thanks for the reply. 

While the 0.20 client works I cant get the new 0.20 to work properly I think. When I install and run 0.20 with the rest of the clients not sound plays even `sudo cat /dev/urandom > /tmp/snapfifo` test fails.

I uninstall snapserver 0.20-develop and reinstall 0.19 from the Debian repo and everything works again. Has there been an undocumented change to the settings maybe? I  am (and have been) using the `pipe:///tmp/snapfifo?mode=read&name=Cast`  which works in 0.19 but 0.20 server gives me no  sound netiehr on the local client (0.20) nor or on the remote clients (0.19).

**Comment by badaix** [comment]
server wise the 0.20 should be almost the same as the 0.19. Can you see anything in the logs (with `logging.filter = debug`)?
