### ISSUE TITLE
Unable to build on arch-linux (Boost 1.75.0)

### ISSUE THREAD

**Issue by lrodorigo** [badaix/snapcast#885]
**Describe the bug**
Snapclient / Snapserver does not compile under Arch Linux - using Boost v1.75.0 and GCC 11.1.

**Steps to Reproduce**
1. generate Makefile from CMakeLists
2. make

**Environment details**
- OS: Arch Linux (just updated)
- Snapcast version (master branch and v 0.25.0)

**Attach logfile if applicable**

```log
[ 10%] Built target common
[ 12%] Building CXX object server/CMakeFiles/snapserver.dir/config.cpp.o
[ 14%] Building CXX object client/CMakeFiles/snapclient.dir/client_connection.cpp.o
[ 16%] Building CXX object server/CMakeFiles/snapserver.dir/control_server.cpp.o
[ 18%] Building CXX object client/CMakeFiles/snapclient.dir/controller.cpp.o
In file included from /home/luiss/workspace/snapcast/server/control_server.cpp:19:
/home/luiss/workspace/snapcast/server/control_server.hpp:46:42: error: expected ‘)’ before ‘&’ token
   46 |     ControlServer(boost::asio::io_context& io_context, const ServerSettings::Tcp& tcp_settings, const ServerSettings::Http& http_settings,
      |                  ~                       ^
      |                                          )
In file included from /home/luiss/workspace/snapcast/server/control_server.cpp:19:
/home/luiss/workspace/snapcast/server/control_server.hpp:74:18: error: ‘io_context’ in namespace ‘boost::asio’ does not name a type; did you mean ‘is_const’?
   74 |     boost::asio::io_context& io_context_;
      |                  ^~~~~~~~~~
      |                  is_const
In file included from /usr/include/boost/beast/core/detail/bind_handler.hpp:15,
                 from /usr/include/boost/beast/core/bind_handler.hpp:14,
                 from /usr/include/boost/beast/core/async_base.hpp:14,
                 from /usr/include/boost/beast/core.hpp:15,
                 from /home/luiss/workspace/snapcast/server/control_session_http.hpp:23,
                 from /home/luiss/workspace/snapcast/server/control_server.cpp:24:
/usr/include/boost/asio/associated_allocator.hpp:33:39: error: expected ‘;’ at end of member declaration
   33 |   static type get(const T&, const E& e) BOOST_ASIO_NOEXCEPT
      |                                       ^
      |                                        ;
/usr/include/boost/asio/associated_allocator.hpp:33:41: error: ‘BOOST_ASIO_NOEXCEPT’ does not name a type; did you mean ‘BOOST_NOEXCEPT’?
   33 |   static type get(const T&, const E& e) BOOST_ASIO_NOEXCEPT
      |                                         ^~~~~~~~~~~~~~~~~~~
      |                                         BOOST_NOEXCEPT
/usr/include/boost/asio/associated_allocator.hpp:41:55: error: template argument 3 is invalid
   41 |   typename void_type<typename T::allocator_type>::type>
      |                                                       ^
/usr/include/boost/asio/associated_allocator.hpp:86:39: error: expected ‘;’ at end of member declaration
   86 |       const Allocator& a = Allocator()) BOOST_ASIO_NOEXCEPT
      |                                       ^
```
... and tons of similar errors.

**Comment by badaix** [comment]
`boost::asio::io_context` is declared in `boost/asio/io_context.hpp`, which is included by `boost/asio.hpp`, which is included by `control_server.hpp` and fully qualified used in the constructor
```c++
ControlServer(boost::asio::io_context& io_context, const ServerSettings::Tcp& tcp_settings, const ServerSettings::Http& http_settings,
                  ControlMessageReceiver* controlMessageReceiver = nullptr);
```
and these messages are coming from boost itself:
```c++
/usr/include/boost/asio/associated_allocator.hpp:33:39: error: expected ‘;’ at end of member declaration
   33 |   static type get(const T&, const E& e) BOOST_ASIO_NOEXCEPT
      |                                       ^
      |                                        ;
/usr/include/boost/asio/associated_allocator.hpp:33:41: error: ‘BOOST_ASIO_NOEXCEPT’ does not name a type; did you mean ‘BOOST_NOEXCEPT’?
   33 |   static type get(const T&, const E& e) BOOST_ASIO_NOEXCEPT
      |                                         ^~~~~~~~~~~~~~~~~~~
      |                                         BOOST_NOEXCEPT
/usr/include/boost/asio/associated_allocator.hpp:41:55: error: template argument 3 is invalid
   41 |   typename void_type<typename T::allocator_type>::type>
      |                                                       ^
/usr/include/boost/asio/associated_allocator.hpp:86:39: error: expected ‘;’ at end of member declaration
   86 |       const Allocator& a = Allocator()) BOOST_ASIO_NOEXCEPT
```

So I would guess that your boost installation is broken.

**Comment by lrodorigo** [comment]
You're right.
My Boost installation seems to be fine but I had a Boost v1.58.0 in
/usr/local/{lib,include} (and Boost v.1.75 in /usr/{lib,include}), so I
think there is still a strange behaviour with CMake, since it was reporting
"found Boost v 1.75.0", while it seems that the compiler was sing the
includes from the 1.58.0 instead.
Tried also with ```cmake -DBOOST_ROOT=/usr/``` but nothing changed.

Solved by (temporarily) renaming the `/usr/local/include/boost` folder and
then running the CMake.
